name: i18n-weekly-pull

on:
  schedule:
    # run every monday at 2AM
    - cron: '0 2 * * 1'

jobs:
  pull-from-transifex:
    # This workflow is only of value to the arduino/arduino-ide repository and
    # would always fail in forks
    if: github.repository == 'arduino/arduino-ide'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Run i18n:pull script
        run: yarn run i18n:pull
        env:
          TRANSIFEX_ORGANIZATION: ${{ secrets.TRANSIFEX_ORGANIZATION }}
          TRANSIFEX_PROJECT: ${{ secrets.TRANSIFEX_PROJECT }}
          TRANSIFEX_RESOURCE: ${{ secrets.TRANSIFEX_RESOURCE }}
          TRANSIFEX_API_KEY: ${{ secrets.TRANSIFEX_API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Updated translation files
          title: Updated translation files
          branch: i18n/translations-update
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
